### ISSUE TITLE
GET and POST are only supported methods for form submissions

### ISSUE THREAD

**Issue by ansongoldade** [lynx-json/jsua-lynx#24]
The following code exists in the `submit` view builder to set the method.
`if (node.value.method) view.formMethod = node.value.method;`

The issue is that the `formMethod` value only supports `GET` and `POST` methods per the HTML5 specification.
https://www.w3.org/TR/html5/forms.html#attr-fs-formmethod

Therefore, we can not currently support PUT or DELETE methods. Not sure if this is an issue or not, but I ran into it trying to use a DELETE method and it changed that value to GET. If we choose not to make any changes to support the additional methods then we should document that they are unsupported.

Personally, PUT is not that important to me, but I would like to able to use DELETE where the method semantics line up to what the application server is doing.

**Comment by danmork** [comment]
I'm not opposed to a change that would enable support for HTTP methods other than GET/POST as long as it works with fetch and the fetch polyfills we're using. Submit a PR and I'll review it.

**Comment by ansongoldade** [comment]
Seems like they should be allowed based on the following in the Fetch standard.
https://fetch.spec.whatwg.org/#concept-method

I'll put together a pull request for this later on this week.

**Comment by ansongoldade** [comment]
Resolved with PR #25
