### ISSUE TITLE
`container` with child that is `null` fails to build

### ISSUE THREAD

**Issue by ansongoldade** [lynx-json/jsua-lynx#30]
The following document fails to build. 

```json
{"realm":"http://example.com/","spec":{"hints":["container"],"children":[{"name":"link" }] },"link":null }
```

Not clear to me if this is a valid document or not since the child exists in the children array but it doesn't have hints defined anywhere in the document. 

This is a separate error from issue #29.

**Comment by danmork** [comment]
The Lynx+JSON in the example is invalid, because:

> The hints property is REQUIRED when referring to a value that does not have its own spec property. Otherwise, the hints property is OPTIONAL.

http://lynx-json.org/specification/specifications/properties/hints/

**Comment by ansongoldade** [comment]
Makes sense. I'll open a separate issue for discussion in lynx-docs about whether it makes sense to add this check to the lynx linter.
